version: 1.0
services:
  test: 
    is_production: true
    force_delete: yes
    
    daemon_address: http://192.168.1.194:8080
    site_id: 1
    app_path: /TestIIS
    
    bundle_dir: test
    log_dir: logs
    
    build:
      work_dir: ../Webion.IIS.Daemon
      command: |
        dotnet publish -c Release
        echo 'Done'
