services:
  kaire: 
    is_production: yes
    daemon_address: http://192.168.1.194:8080
    site_id: 1
    app_path: /webion/TestIIS
    
    delete_directory: true
    bundle_dir: out/Webion.IIS.Daemon
    log_dir: logs
    
    build:
      command: dotnet
      args: ["publish", "-o", "out"]
      work_dir: ../Webion.IIS.Daemon