version: 1.0
services:
  test:
    envs:
      - name: default
        daemon_address: http://192.168.1.194:8080
        is_production: no
        site_id: 1
        app_path: /kaire/trace/ui
        log_dir: ./logs
  
    bundle_dir: test
    build:
      - name: 'Publish' 
        work_dir: ../Webion.IIS.Daemon
        run: |
          dotnet publish -c Release 